### PR TITLE
Refs #7800. Added support for service_instance_name.

### PR DESCRIPTION
**Pull request by richiware**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-dds-linux/36/)

**Review by LuisGP — DISMISSED** [review]

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-dds-linux/37/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss-dds-linux/38/)

**Review by jamoralp — APPROVED** [review]
LGTM

**Pull request merged**
